const $ = s => document.querySelector(s);
const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session, profile, employees = [], hours = 80, version = 0;
const statuses = {completed:'Завершено',in_progress:'В процессе',no_show:'Пропуск',declined:'Отказ',dropped:'Прервано',overdue:'Просрочено'};
const formats = {online:'Онлайн',offline:'Очно',self_paced:'В своём темпе'};
async function api(path, payload) {
  const res = await fetch(path, payload === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const data = await res.json(); if (!res.ok) throw Error(data.error || 'Ошибка запроса'); return data;
}
function toast(message) { $('#toast').textContent = message; $('#toast').style.display='block'; setTimeout(()=>$('#toast').style.display='none',5000); }
async function login(role='employee') {
  try { employees = (await api('/api/demo')).employees; $('#employee-select').innerHTML = employees.map(e=>`<option value="${esc(e.employee_id)}">${esc(e.full_name)} · ${esc(e.role)} (${esc(e.employee_id)})</option>`).join(''); $('#login-role').value=role; toggleRole(); $('#login-error').textContent=''; if (!$('#login').open) $('#login').showModal(); } catch(e){toast(e.message);}
}
function toggleRole(){const hr=$('#login-role').value==='hr';$('#employee-label').hidden=hr;$('#password-label').hidden=!hr;}
$('#login-role').onchange=toggleRole;
$('#login').addEventListener('cancel', e=>{if(!session)e.preventDefault();});
$('#login-form').onsubmit=async e=>{e.preventDefault();try{session=await api('/api/login',{role:$('#login-role').value,employee_id:$('#employee-select').value,password:$('#hr-password').value});$('#login').close();$('#hr-password').value='';session.role==='hr'?await showHR():await showProfile();}catch(err){$('#login-error').textContent=err.message;}};
$('#switch').onclick=()=>login();
$('#nav-career').onclick=()=>session?.role==='employee'?showProfile():login();
$('#nav-hr').onclick=()=>session?.role==='hr'?showHR():login('hr');
function nav(hr){$('#nav-career').classList.toggle('active',!hr);$('#nav-hr').classList.toggle('active',hr);}
async function showProfile(){
 const request=++version;nav(false);$('#app').innerHTML='<p class="muted">Собираем траекторию…</p>';
 try{const p=await api(`/api/profile?hours=${hours}`);if(request!==version)return;profile=p;renderProfile();}catch(e){$('#app').textContent=e.message;}
}
function card(c,i){return `<article class="card"><div class="card-top"><span class="pill">${i===0?'✧ Лучший следующий шаг':'Вариант '+(i+1)}</span><span>${c.duration_hours} ч · ${esc(formats[c.format])}</span></div><h3>${esc(c.title)}</h3><p class="description">${esc(c.description)}</p><div class="gain">↗ +${c.delta} п.п. к покрытию цели</div><div class="muted">${c.format==='self_paced'?'Можно начать сегодня':'Ближайшая сессия: '+esc(c.upcoming_sessions.find(d=>d>=profile.as_of_date))}</div><details><summary>Почему именно этот шаг?</summary><ul>${c.explanation.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><span class="muted">Модель участия — оценка по истории, не гарантия. Балл выбора: ${c.score}.</span></details><button class="secondary" data-preview="${esc(c.event_id)}">Что изменится? ↗</button><button class="primary" data-complete="${esc(c.event_id)}">Симулировать выполнение ✓</button></article>`;}
function renderProfile(){const p=profile,e=p.employee;const critical=p.gaps.filter(g=>g.critical&&g.gap).length;
 $('#app').innerHTML=`<section class="hero"><div><span class="eyebrow">ТВОЯ КАРЬЕРА — ТВОЙ МАРШРУТ</span><h2>${esc(e.full_name)}</h2><p>${esc(e.role)} · ${esc(e.grade)} · ${esc(e.tenure_months??'—')} мес. в команде</p><span class="pill">◎ Цель: ${esc(p.target.role)} / ${esc(p.target.grade)}</span><div class="timeline"><b>${esc(e.grade)}</b><span>─────</span><b class="target">${esc(p.target.grade)}</b><span>Траектория по навыкам</span></div></div><div class="ring" style="--progress:${p.readiness}"><div class="ring-inner"><strong>${p.readiness}%</strong><span>покрытие цели</span></div></div></section>
 <div class="metrics"><div class="metric"><strong>${critical}</strong><span>Критических разрывов</span></div><div class="metric"><strong>${p.completed_count}</strong><span>Завершённых активностей</span></div><div class="metric"><strong>${p.recommendations.length}</strong><span>Шага на выбор</span></div></div>
 <div class="section-head"><div><h2>Маленький шаг. Видимый рост.</h2><p>Рекомендации с учётом твоей цели и истории участия</p></div><label>Время на одну активность<select id="hours">${[4,8,16,40,80].map(n=>`<option ${n===hours?'selected':''} value="${n}">До ${n} часов</option>`).join('')}</select></label></div>
 <div class="cards">${p.recommendations.length?p.recommendations.map(card).join(''):`<div class="empty wide">${esc(p.no_step_reason)}</div>`}</div>
 <div class="columns"><section class="panel"><h3>Карта навыков</h3><p class="muted">Текущий уровень / требование цели. Критические навыки имеют двойной вес в расчёте покрытия.</p>${p.gaps.map(g=>`<div class="skill"><div class="skill-label"><span>${esc(g.name)} ${g.critical?'<span class="critical">◆ критический</span>':''}</span><b>${g.current} / ${g.required}</b></div><div class="bar"><i style="width:${g.required?Math.min(100,g.current/g.required*100):100}%"></i></div></div>`).join('')}</section><section class="panel"><h3>Твой путь уже начался</h3><p class="muted">Последние 20 записей. Обучение после оценки ${esc(e.last_review_date)} учтено в навыках.</p>${p.history.map(r=>`<div class="history-row"><strong>${esc(r.title)}</strong><span>${esc(r.date)} · ${esc(statuses[r.status]||r.status)} ${r.simulated?'· симуляция':''}</span></div>`).join('')||'<p>История пока пуста.</p>'}</section></div>
 <details class="audit"><summary>Прозрачность: почему другие активности не предложены</summary>${p.excluded.map(c=>`<p><b>${esc(c.title)}</b><br>${c.reasons.map(esc).join(' · ')}</p>`).join('')}${p.alternatives.map(c=>`<p><b>${esc(c.title)}</b> · доступно, но ниже в ранжировании: ${c.score} · +${c.delta} п.п.</p>`).join('')}</details>`;
 $('#hours').onchange=e=>{hours=Number(e.target.value);showProfile();};
 document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview));
 document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>complete(b));
}
function preview(id){const c=profile.recommendations.find(c=>c.event_id===id);$('#simulation-content').innerHTML=`<span class="eyebrow">ЕСЛИ ПРОЙТИ ЭТУ АКТИВНОСТЬ</span><h2>${esc(c.title)}</h2><div class="preview-number">${profile.readiness}% → ${c.readiness_after}%</div><p>Покрытие требований к ${esc(profile.target.grade)}</p><table><thead><tr><th>Навык</th><th>Сейчас</th><th>После</th><th>Цель</th></tr></thead><tbody>${c.changes.map(g=>`<tr><td>${esc(g.name)}</td><td>${g.before}</td><td>${g.after}</td><td>${g.required||'—'}</td></tr>`).join('')}</tbody></table><p class="muted">Расчёт по gain и max_level из каталога. Это модель развития; решение о повышении принимает человек после оценки компетенций.</p>`;$('#simulation').showModal();}
$('#close-simulation').onclick=()=>$('#simulation').close();
async function complete(button){button.disabled=true;try{await api('/api/complete',{event_id:button.dataset.complete});await showProfile();toast('Симуляция сохранена. Навыки и рекомендации пересчитаны.');}catch(e){toast(e.message);button.disabled=false;}}
async function showHR(){const request=++version;nav(true);$('#app').innerHTML='<p class="muted">Считаем срез команды…</p>';try{const h=await api('/api/hr');if(request!==version)return;
 $('#app').innerHTML=`<section class="hero"><div><span class="eyebrow">HR WORKSPACE</span><h2>Помочь каждому расти.</h2><p>Где не хватает навыков и возможностей для развития</p><span class="pill">Агрегированный обзор · без публичного рейтинга</span></div></section><div class="metrics"><div class="metric"><strong>${h.employees}</strong><span>Сотрудников</span></div><div class="metric"><strong>${h.blocked.length}</strong><span>Без доступного шага</span></div><div class="metric"><strong>${h.participation.completed||0}</strong><span>Завершений в истории</span></div></div><div class="columns"><section class="panel"><h3>Частые разрывы по навыкам</h3><p class="muted">Количество сотрудников с разрывом относительно своей цели</p>${h.gaps.map(g=>`<div class="skill"><div class="skill-label"><span>${esc(g.name)}</span><b>${g.count}</b></div><div class="bar"><i style="width:${100*g.count/h.employees}%"></i></div></div>`).join('')}</section><section class="panel"><h3>Кому нужен индивидуальный маршрут</h3><p class="muted">Недостаток подходящих событий — сигнал расширить каталог, а не оценка сотрудника.</p><div class="table-scroll">${h.blocked.map(e=>`<div class="history-row"><strong>${esc(e.name)} · ${esc(e.employee_id)}</strong><span>${esc(e.reason)}</span></div>`).join('')||'<p>Для всех есть подходящий шаг.</p>'}</div><h3>Участие</h3>${Object.entries(h.participation).map(([k,v])=>`<p class="muted">${esc(statuses[k]||k)}: <b>${v}</b></p>`).join('')}</section><section class="panel wide"><h3>Каталог и завершения</h3><div class="table-scroll"><table><thead><tr><th>Активность</th><th>Записей участия</th><th>Завершено</th></tr></thead><tbody>${h.events.map(e=>`<tr><td>${esc(e.title)}</td><td>${e.participants}</td><td>${e.completed}</td></tr>`).join('')}</tbody></table></div></section><section class="panel wide"><h3>Проверочные профили жюри</h3><p class="muted">Импорт объединяет записи по employee_id и record_id. Существующие записи с тем же ID обновляются. Проверка выполняется до сохранения.</p><form id="import-form"><div class="import-grid"><label>employees.json<input id="employees-file" type="file" accept=".json"></label><label>activity_history.csv<input id="history-file" type="file" accept=".csv"></label></div><button class="primary">Проверить и импортировать</button></form></section></div>`;
 $('#import-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const ef=$('#employees-file').files[0],hf=$('#history-file').files[0];if(!ef&&!hf)throw Error('Выберите хотя бы один файл');const raw=ef?JSON.parse(await ef.text()):[];const result=await api('/api/import',{employees:raw,history:hf?await hf.text():[]});toast(`Импортировано: ${result.employees} профилей, ${result.history} записей`);await showHR();}catch(err){toast(err.message);b.disabled=false;}};
 }catch(e){$('#app').textContent=e.message;}}
login();
